import type { DesignSettings, Position } from "./types";

export const FONTS = [
  { label: "Inter", css: "Inter, sans-serif" },
  { label: "Poppins", css: "Poppins, sans-serif" },
  { label: "Montserrat", css: "Montserrat, sans-serif" },
  { label: "Roboto", css: "Roboto, sans-serif" },
  { label: "Playfair Display", css: "'Playfair Display', serif" },
  { label: "Oswald", css: "Oswald, sans-serif" },
  { label: "Bebas Neue", css: "'Bebas Neue', sans-serif" },
  { label: "Lora", css: "Lora, serif" },
  { label: "Merriweather", css: "Merriweather, serif" },
  { label: "Anton", css: "Anton, sans-serif" },
] as const;

export const POSITIONS: { value: Position; label: string }[] = [
  { value: "top-left", label: "Top left" },
  { value: "top-center", label: "Top" },
  { value: "top-right", label: "Top right" },
  { value: "center-left", label: "Center left" },
  { value: "center", label: "Center" },
  { value: "center-right", label: "Center right" },
  { value: "bottom-left", label: "Bottom left" },
  { value: "bottom-center", label: "Bottom" },
  { value: "bottom-right", label: "Bottom right" },
];

export const DEFAULT_SETTINGS: DesignSettings = {
  fontFamily: "Montserrat, sans-serif",
  autoFit: true,
  fontSize: 64,
  position: "center",
  align: "center",
  color: "#ffffff",
  opacity: 1,
  bold: true,
  italic: false,
  letterSpacing: 0,
  lineHeight: 1.25,
  shadow: true,
  shadowBlur: 24,
  shadowOpacity: 0.5,
  shadowOffset: 4,
  outline: false,
  outlineWidth: 3,
  outlineColor: "#111827",
  background: "none",
  backgroundColor: "#111827",
  backgroundOpacity: 0.45,
  backgroundRadius: 24,
  backgroundPadding: 28,
};

export type StylePreset = { name: string; description: string; settings: Partial<DesignSettings> };

export const STYLE_PRESETS: StylePreset[] = [
  {
    name: "Minimal",
    description: "Clean typography, no distractions.",
    settings: {
      fontFamily: "Inter, sans-serif",
      bold: false,
      shadow: false,
      outline: false,
      background: "none",
      letterSpacing: 1,
      position: "bottom-center",
      color: "#ffffff",
    },
  },
  {
    name: "Bold",
    description: "Large high-impact typography.",
    settings: {
      fontFamily: "Anton, sans-serif",
      bold: true,
      shadow: true,
      shadowBlur: 30,
      outline: false,
      background: "none",
      position: "center",
      letterSpacing: 0,
      lineHeight: 1.1,
    },
  },
  {
    name: "Luxury",
    description: "Elegant type with premium spacing.",
    settings: {
      fontFamily: "'Playfair Display', serif",
      bold: false,
      italic: false,
      letterSpacing: 6,
      lineHeight: 1.5,
      shadow: false,
      background: "translucent",
      backgroundColor: "#111827",
      backgroundOpacity: 0.3,
      position: "center",
      color: "#ffffff",
    },
  },
  {
    name: "Modern",
    description: "Contemporary social-media style.",
    settings: {
      fontFamily: "Poppins, sans-serif",
      bold: true,
      shadow: true,
      shadowBlur: 18,
      background: "none",
      position: "bottom-left",
      align: "left",
      letterSpacing: 0,
    },
  },
  {
    name: "Quote Card",
    description: "Made for inspirational quotes.",
    settings: {
      fontFamily: "Lora, serif",
      bold: false,
      italic: true,
      background: "translucent",
      backgroundOpacity: 0.5,
      backgroundRadius: 32,
      backgroundPadding: 40,
      position: "center",
      lineHeight: 1.4,
      shadow: false,
    },
  },
  {
    name: "Business",
    description: "Professional marketing typography.",
    settings: {
      fontFamily: "Montserrat, sans-serif",
      bold: true,
      letterSpacing: 2,
      background: "solid",
      backgroundColor: "#0f172a",
      backgroundOpacity: 1,
      backgroundRadius: 8,
      backgroundPadding: 26,
      position: "bottom-center",
      shadow: false,
    },
  },
  {
    name: "Instagram",
    description: "Optimised for Instagram posts.",
    settings: {
      fontFamily: "Oswald, sans-serif",
      bold: true,
      letterSpacing: 1,
      shadow: true,
      shadowBlur: 22,
      position: "center",
      align: "center",
      lineHeight: 1.2,
      background: "none",
    },
  },
  {
    name: "Pinterest",
    description: "Optimised for tall Pinterest graphics.",
    settings: {
      fontFamily: "Merriweather, serif",
      bold: true,
      background: "translucent",
      backgroundOpacity: 0.55,
      backgroundRadius: 18,
      backgroundPadding: 34,
      position: "top-center",
      lineHeight: 1.35,
      shadow: false,
    },
  },
];
